name: BetterAssociations
main: com.sandislandserv.rourke750.BetterAssociations
version: .62
author: Rourke750
softdepend: [PrisonPearl]
commands:
   ba:
      description: main command for Better Associations
      usage: /<command> <args>
      permission: betterassociations.ba
permissions:
   betterassociations.ba:
      description: Gives access to the ba command.
      default: op